import { FamilyGroup, Transaction, FixedExpenseItem, PiggyBankItem } from '../types';


export const INITIAL_GROUP: FamilyGroup = {
  id: 'group-wepay-demo',
  name: 'Thiago & Mariana',
  code: 'WEPAY-2026',
  monthlyBudget: 5000.00,
  currency: 'BRL',
  createdAt: new Date().toISOString(),
  members: [
    {
      id: 'member-1',
      name: 'Thiago',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      color: '#3b82f6', // Indigo Blue
      email: 'thiago@wepay.app',
      role: 'admin',
      income: 4500,
    },
    {
      id: 'member-2',
      name: 'Mariana',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
      color: '#ec4899', // Vibrant Pink
      email: 'mariana@wepay.app',
      role: 'admin',
      income: 4800,
    }
  ]
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    description: 'Feira do Mês no Carrefour',
    amount: 485.90,
    category: 'Alimentação',
    categoryIcon: 'ShoppingCart',
    type: 'expense',
    paidByMemberId: 'member-1', // Thiago paid
    splitType: 'equal',
    date: new Date(Date.now() - 86400000 * 1).toISOString(), // 1 day ago
    aiCategorized: true,
  },
  {
    id: 'tx-2',
    description: 'Conta de Energia Elétrica (Enel)',
    amount: 154.30,
    category: 'Moradia',
    categoryIcon: 'Zap',
    type: 'expense',
    paidByMemberId: 'member-2', // Mariana paid
    splitType: 'equal',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    aiCategorized: true,
  },
  {
    id: 'tx-3',
    description: 'Jantar Romântico no Bistrô',
    amount: 210.00,
    category: 'Alimentação',
    categoryIcon: 'Utensils',
    type: 'expense',
    paidByMemberId: 'member-1',
    splitType: 'equal',
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    aiCategorized: true,
  },
  {
    id: 'tx-4',
    description: 'Uber para o Trabalho',
    amount: 32.50,
    category: 'Transporte',
    categoryIcon: 'Car',
    type: 'expense',
    paidByMemberId: 'member-2',
    splitType: 'individual',
    date: new Date(Date.now() - 86400000 * 4).toISOString(),
    aiCategorized: false,
  },
  {
    id: 'tx-5',
    description: 'Assinatura Netflix & Spotify',
    amount: 55.90,
    category: 'Lazer',
    categoryIcon: 'Tv',
    type: 'expense',
    paidByMemberId: 'member-2',
    splitType: 'equal',
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
    isRecurrent: true,
    aiCategorized: true,
  }
];

export const INITIAL_FIXED_EXPENSES: FixedExpenseItem[] = [
  {
    id: 'fx-1',
    title: 'Aluguel do Apartamento',
    amount: 1800.00,
    category: 'Moradia',
    paidByMemberId: 'member-1',
    dueDate: '10',
    isPaid: true,
    recurrenceType: 'fixed_amount',
    monthKey: '2026-08',
    notes: 'Incluso taxa de condomínio',
  },
  {
    id: 'fx-2',
    title: 'Conta de Energia (Luz)',
    amount: 195.40,
    category: 'Moradia',
    paidByMemberId: 'member-2',
    dueDate: '15',
    isPaid: false,
    recurrenceType: 'variable_amount',
    monthKey: '2026-08',
    notes: 'Valor varia conforme consumo',
  },
  {
    id: 'fx-3',
    title: 'Internet Wi-Fi Fibra',
    amount: 120.00,
    category: 'Moradia',
    paidByMemberId: 'member-1',
    dueDate: '08',
    isPaid: true,
    recurrenceType: 'fixed_amount',
    monthKey: '2026-08',
  },
  {
    id: 'fx-4',
    title: 'Faculdade / Pós-Graduação',
    amount: 650.00,
    category: 'Educação',
    paidByMemberId: 'member-2',
    dueDate: '20',
    isPaid: false,
    recurrenceType: 'fixed_amount',
    monthKey: '2026-08',
  },
  {
    id: 'fx-5',
    title: 'Plano de Saúde Familiar',
    amount: 420.00,
    category: 'Saúde',
    paidByMemberId: 'member-1',
    dueDate: '25',
    isPaid: false,
    recurrenceType: 'fixed_amount',
    monthKey: '2026-08',
  },
  {
    id: 'fx-6',
    title: 'Sofá Retrátil da Sala',
    amount: 320.00,
    category: 'Moradia',
    paidByMemberId: 'member-2',
    dueDate: '12',
    isPaid: false,
    recurrenceType: 'installment',
    monthKey: '2026-08',
    startMonthKey: '2026-08',
    endMonthKey: '2027-05',
    totalInstallments: 10,
    notes: 'Compra parcelada em 10x sem juros',
  },
];

export const INITIAL_PIGGY_BANKS: PiggyBankItem[] = [
  {
    id: 'piggy-1',
    title: 'Viagem em Família',
    currentAmount: 3100,
    targetAmount: 5000,
    icon: 'Plane',
    colorTheme: 'purple',
    notes: 'Reserva para as férias do fim de ano',
  },
  {
    id: 'piggy-2',
    title: 'Casa Própria (Entrada)',
    currentAmount: 4800,
    targetAmount: 10000,
    icon: 'Home',
    colorTheme: 'blue',
    notes: 'Meta para dar entrada no apartamento',
  },
  {
    id: 'piggy-3',
    title: 'Faculdade / Pós',
    currentAmount: 6000,
    targetAmount: 8000,
    icon: 'GraduationCap',
    colorTheme: 'emerald',
    notes: 'Fundo para pagamento do semestre',
  },
  {
    id: 'piggy-4',
    title: 'Reserva de Emergência',
    currentAmount: 8500,
    targetAmount: 15000,
    icon: 'Shield',
    colorTheme: 'amber',
    notes: 'Garante 3 meses de custos fixos do casal',
  },
  {
    id: 'piggy-5',
    title: 'Carro Novo',
    currentAmount: 12000,
    targetAmount: 30000,
    icon: 'Car',
    colorTheme: 'rose',
    notes: 'Troca de veículo planejada',
  },
];

